### ISSUE TITLE
Primeira Issue

### ISSUE THREAD

**Issue by luizpnunes** [luizpnunes/GCMS-LUIZ-SILVA#1]
[README](https://github.com/luizpaulonunes2323/GCMS-LUIZ-SILVA/edit/main/README.md)

**Comment by ramidedantas** [comment]
@luizpaulonunes2323 faltou me marcar na issue para eu ser notificado.

**Comment by luizpnunes** [comment]
@ramidedantas, ok professor.

**Comment by ramidedantas** [comment]
@luizpaulonunes2323 pode fechar a issue.
